### PR TITLE
Fix -w behaviour and docs (<https://github.com/petdance/ack2/issues/445>)

### PR DESCRIPTION
**Pull request by epa**

### CODE REVIEW

**Comment by petdance** [comment]
Thanks for the patch.  Something of this magnitude needs some severe test coverage before I can even think of merging it in.

**Comment by epa** [comment]
I will add some tests.

**Comment by petdance** [comment]
I'm also concerned about any potential speed degradations.

The change you're suggesting here needs to be discussed on the ack-users mailing list because it is potentially a huge breakage of existing behavior.  The new -w may be "fixed", but it is changing existing behavior and we have to be very very very careful with that.

**Comment by epa** [comment]
Would you prefer that I first document and test the existing behaviour, and then we can decide whether to change it?

**Comment by petdance** [comment]
I think that makes a lot of sense.  If anything is going to be changed, then there will have to be a clear explanation of that change in the Changes file for any future users.

**Comment by epa** [comment]
I've sent a pull request which documents and tests the current semantics.

**Comment by epa** [comment]
I've posted on ack-user asking about this proposed change to -w semantics.

**Comment by epa** [comment]
Hmm, it looks like my message to ack-users has been rejected - if you're the moderator of that list could you check please?

**Comment by petdance** [comment]
I'm the moderator, and I don't see anything pending.  Try again?

**Comment by epa** [comment]
Here's the delivery failure - do I have the wrong address?

Hello eda@waniasset.com,

We're writing to let you know that the group you tried to contact (ack-users) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

* You might have spelled or formatted the group name incorrectly.
* The owner of the group may have removed this group.
* You may need to join the group before receiving permission to post.
* This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at http://groups.google.com/support/.

Thanks,

Google Groups



----- Original message -----

X-Received: by 10.180.36.172 with SMTP id r12mr7971871wij.6.1434809104399;
        Sat, 20 Jun 2015 07:05:04 -0700 (PDT)
Return-Path: <gcsau-ack-users@m.gmane.org>
Received: from plane.gmane.org (plane.gmane.org. [80.91.229.3])
        by gmr-mx.google.com with ESMTPS id wf6si595885lbb.2.2015.06.20.07.05.04
        for <ack-users@googlegroups.com>
        (version=TLSv1 cipher=RC4-SHA bits=128/128);
        Sat, 20 Jun 2015 07:05:04 -0700 (PDT)
Received-SPF: pass (google.com: domain of gcsau-ack-users@m.gmane.org designates 80.91.229.3 as permitted sender) client-ip=80.91.229.3;
Authentication-Results: gmr-mx.google.com;
       spf=pass (google.com: domain of gcsau-ack-users@m.gmane.org designates 80.91.229.3 as permitted sender) smtp.mail=gcsau-ack-users@m.gmane.org
Received: from list by plane.gmane.org with local (Exim 4.69)
	(envelope-from <gcsau-ack-users@m.gmane.org>)
	id 1Z6JOJ-0007X0-B0
	for ack-users@googlegroups.com; Sat, 20 Jun 2015 16:05:03 +0200
Received: from dsl-217-155-72-22.zen.co.uk ([217.155.72.22])
        by main.gmane.org with esmtp (Gmexim 0.1 (Debian))
        id 1AlnuQ-0007hv-00
        for <ack-users@googlegroups.com>; Sat, 20 Jun 2015 16:05:03 +0200
Received: from eda by dsl-217-155-72-22.zen.co.uk with local (Gmexim 0.1 (Debian))
        id 1AlnuQ-0007hv-00
        for <ack-users@googlegroups.com>; Sat, 20 Jun 2015 16:05:03 +0200
X-Injected-Via-Gmane: http://gmane.org/
To: ack-users@googlegroups.com
From: Ed Avis <eda@waniasset.com>
Subject: Proposed change to -w behaviour
Date: Sat, 20 Jun 2015 13:58:54 +0000 (UTC)
Lines: 44
Message-ID: <loom.20150620T154223-841@post.gmane.org>
Mime-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
X-Complaints-To: usenet@ger.gmane.org
X-Gmane-NNTP-Posting-Host: sea.gmane.org
User-Agent: Loom/3.14 (http://gmane.org/)
X-Loom-IP: 217.155.72.22 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0)

ack's -w flag is intended to match whole words.  However it has some odd
semantics at present:

% mkdir test
% cd test
% for i in box ox oxen ; do echo $i >$i; done
% ack -wl 'ox'
ox
% ack -wl '()ox'
box
ox
% ack -wl 'ox()'
ox
oxen
% ack -wl '(ox)'
box
ox
oxen

Although the parentheses make no difference to what the regular expression
matches in itself, they do affect the -w flag and cause matches to be found
which are not whole word matches.  This is because currently the behaviour
of -w depends on the first and last characters of the regular expression.
If the first character is not itself a word character, then the normal -w
requirement of a word break at the start of the match doesn't apply; and
likewise at the end.

I propose to change this so that -w always requires a word break before the
match, when the *matched string* starts with a word character.  Ditto end.
I believe that this will match the semantics promised by the documentation
of requiring a whole word match.  The above example would match only 'ox'
in all four cases.

Simple usage, where the regexp is a plain word and does not contain any
special characters, would not be affected.  But it would be possible to
search for alternations such as '(foo|bar)' while still requiring a whole-
word match with -w.

Would anyone who is currently using the -w flag care to comment?
A patch with the proposed change is at
<https://github.com/petdance/ack2/pull/558>

--
Ed Avis <eda@waniasset.com>

**Comment by petdance** [comment]
You're not a member of the group.

**Comment by epa** [comment]
Yes sorry I spotted that - will fix, and mark it as non-public on gmane.org (which is what I tried to use to post).

**Comment by epa** [comment]
There haven't been any comments on ack-users.  What is your opinion on the proposed change?

**Comment by petdance** [comment]
https://groups.google.com/forum/#!topic/ack-users/HVKAvkO4G3U

**Comment by petdance** [comment]
I've only skimmed it.  First thing that comes to mind is that we can't change anything related to parentheses until we get the highlighting bug fixed.

**Comment by epa** [comment]
I don't think this is really 'related to parentheses'; the parens are just one example test case that demonstrates the bug (where -w fails to require a whole word match).  Here is another test case:

    mkdir test; cd test
    for i in box ox oxen; do echo $i >$i; done
    ack -w '\w\w'

This should match a two-letter whole word, but it ends up matching all three strings.

**Comment by epa** [comment]
Do you have time for a closer look at the fix?  As I mentioned it is not related to parentheses or any other particular regexp feature; it  fixes the problem that if the given regexp doesn't begin with a word character then the -w flag fails to work.  https://github.com/petdance/ack2/issues/14 is an older bug covering the same issues.

**Comment by hoelzro** [comment]
@petdance What are your thoughts on this moving forward?  No one on ack-users seems to mind that this would change.

**Comment by petdance** [comment]
How does grep handle this?  If you `grep -w mu.`, what behavior do you get?

**Comment by hoelzro** [comment]
$ echo must | ack -w mu.
    must
    $ echo must | grep -w mu.
    (no output)

**Comment by epa** [comment]
As far as I know grep handles it correctly, in that the -w causes it to match whole words (and doesn't depend on whether the regexp given begins or ends with a word character).
````
% mkdir test
% cd test
% echo mu >>t
% echo mux >>t
% echo muxy >>t
% grep -w mu. t
mux
````

**Comment by petdance** [comment]
@epa: We need to stick to facts and not use words like "correct" or "wrong", because that's an opinion, and everyone has an opinion on things but they can get confusing.

**Comment by epa** [comment]
I do agree, which is why I clarified exactly what I meant by 'correct' in this case.

**Comment by epa** [comment]
Somewhat related: https://rt.perl.org/Public/Bug/Display.html?id=127670

**Comment by petdance** [comment]
The behavior of `-w` is not going to change in ack2.  It is updated in ack3.

**Pull request closed without merging**
