### PR TITLE
Added --output test script #532

### PR DESCRIPTION
**Pull request by Varadinsky**
Part of my pull request challenge for this month. :-)

### CODE REVIEW

**Comment by hoelzro** [comment]
Looks good to me! @petdance any thoughts?

**Comment by petdance** [comment]
Nice.  It looks pretty complete, although I think I'd feel a bit better if there were also tests where it finds more than one hit in more than one file.  I think we can merge this and then add to it.  And make sure we put in a credit for Varadinsky in the ACKnowledgements.

**Comment by hoelzro** [comment]
Merged! @Varadinsky How would you like to be referred to in the acknowledgements?

@petdance Is a new test file Changes-worthy?

**Comment by hoelzro** [comment]
@petdance I just added it to Changes, since we can always pull it out if needed.

**Comment by Varadinsky** [comment]
Thanks! 
@petdance - I will add some more tests to t/ack-output.t.
@hoelzro - Varadinsky is fine. :-)

**Pull request merged**
