### PR TITLE
add extension 'gmk' for type 'make'

### PR DESCRIPTION
**Pull request by francoijs**

### CODE REVIEW

**Comment by petdance** [comment]
Tell me more about this.  I've never heard of .gmk being used for make.  Who uses it?

**Comment by McArcady** [comment]
It is used for GNU make Makefile fragments, just like 'mk'. 
It's the first time i meet this extension too. It is not very widespread. There are a few references on the web, mainly for projects openjdk and geant4.

**Comment by petdance** [comment]
I'd rather not add a default extension to ack for something that's not in widespread use.

**Comment by McArcady** [comment]
Ok I think you right:
After some research, it seems that this extension is not really used anywhere else that in openjdk, 
so I will use option --type-add for searching in gmk files instead.

**Comment by petdance** [comment]
Sounds good.  Remember that you have three different places that you can put that `--type-add`, in three different .ackrc files.  /etc/ackrc, ~/.ackrc, and a project-level .ackrc.

**Pull request closed without merging**
